---
title: "R Notebook"
output: 
  html_notebook: 
    number_sections: yes
---

```{r, message=FALSE}
rm(list = ls())
library(tidyverse); library(ggthemes); library(viridis)
load("../data/1 Cleaned files for analysis/asiData.RDA")
asiSumData <- asiData %>% 
        group_by(finalId, year) %>% ##summarising by the final id var
        summarise(nFactories = sum(mult * x1, na.rm = T), totPersonsEngaged = sum(mult * x8, na.rm = T), totValOutput = sum(mult * x19, na.rm = T)) %>% 
        mutate(year = ifelse(year == 2010, 2011, year)) %>%  # to match the year on the spatial dataset
        ungroup()
```

##Number of non zero outcomes by year

```{r}
asiSumData %>% 
        group_by(year) %>% 
        summarise(nFactories = sum(nFactories != 0, na.rm = T), personsEngaged = sum(totPersonsEngaged != 0, na.rm = T), totValOutput = sum(totValOutput !=0, na.rm = T))
```

##Number of factories
```{r}
asiSumData %>% 
        group_by(year) %>% 
        summarise(meanFactories = mean(nFactories, na.rm = T), maxFactories = max(nFactories, na.rm = T), minFactories = min(nFactories, na.rm = T), sd = sd(nFactories, na.rm = T))
```


```{r, fig.align='center'}
asiSumData %>% 
        ggplot() +
        geom_density(aes(nFactories)) +
        facet_wrap(~year) +
        labs(x = "Number of Factories", y = "Density") +
        theme_tufte() +
        theme(strip.text.x = element_text(size = 14))
        
```

##Number of employees
```{r}
asiSumData %>% 
        group_by(year) %>% 
        summarise(meanEmp = mean(totPersonsEngaged, na.rm = T), maxEmp = max(totPersonsEngaged, na.rm = T), minEmp = min(totPersonsEngaged, na.rm = T), sd = sd(nFactories, na.rm = T))
```


```{r}
asiSumData %>% 
        ggplot() +
        geom_density(aes(totPersonsEngaged)) +
        facet_wrap(~year) +
        labs(x = "Number of Persons Employed", y = "Density") +
        theme_tufte() +
        theme(strip.text.x = element_text(size = 14))
```
